// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prototype_database.Dal;

namespace prototype_database.Dal.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20180827063628_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("prototype_database.Dal.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("OrganizationId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Groups");

                    b.HasData(
                        new { Id = new Guid("3e88800d-17b1-4de3-aecc-a4a3960ff059"), Name = "Technical", OrganizationId = new Guid("a316c1e5-5521-487a-8588-d5c8c0014467") },
                        new { Id = new Guid("3776f864-6f67-4e75-b79b-8dc66ef1c79a"), Name = "HR", OrganizationId = new Guid("a316c1e5-5521-487a-8588-d5c8c0014467") },
                        new { Id = new Guid("14c5836f-285b-4f10-b3c3-03f35aa84146"), Name = "SoftwareEngineer", OrganizationId = new Guid("fcb82b85-8646-4ed4-a410-29ee0c03893a") },
                        new { Id = new Guid("f13be28b-8509-408e-841d-03d900d73435"), Name = "ComputerEngineer", OrganizationId = new Guid("fcb82b85-8646-4ed4-a410-29ee0c03893a") }
                    );
                });

            modelBuilder.Entity("prototype_database.Dal.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new { Id = new Guid("a316c1e5-5521-487a-8588-d5c8c0014467"), Name = "Rosen" },
                        new { Id = new Guid("fcb82b85-8646-4ed4-a410-29ee0c03893a"), Name = "UIT" }
                    );
                });

            modelBuilder.Entity("prototype_database.Dal.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = new Guid("6424b41c-136f-4347-ac47-18a672fad8e0"), Name = "Technical Lead" },
                        new { Id = new Guid("4b7a6ca9-03c0-4e2c-a856-f05e87a95e31"), Name = "HR Lead" },
                        new { Id = new Guid("03ffbf68-6df8-4ea5-a2b3-101e865d34a9"), Name = "Engineer" }
                    );
                });

            modelBuilder.Entity("prototype_database.Dal.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Mobile");

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("Phone");

                    b.Property<string>("ProfileImage");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("prototype_database.Dal.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("GroupId");

                    b.Property<bool>("IsMain");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("prototype_database.Dal.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsMain");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("prototype_database.Dal.Group", b =>
                {
                    b.HasOne("prototype_database.Dal.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("prototype_database.Dal.User", b =>
                {
                    b.HasOne("prototype_database.Dal.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
